(* ==================================================================== *)
(* Rocq 9.2 Formal Theory for CL0 / R0 Dual Carrier Confluence & Lemmas *)
(* Generated by CL0/R0 Core Engine Proof Synthesizer                    *)
(* Module: CL0_Formal_Rocq                                                   *)
(* ==================================================================== *)

Inductive sort : Set :=
| S_State : sort
| S_Interval : sort
| S_Storage : sort
| S_Node : sort
| S_Fact : sort.

Inductive cl0_fun : Set :=
| F_Conf : cl0_fun
| F_Pair : cl0_fun
| F_Trim : cl0_fun
| F_Split : cl0_fun
| F_Runtime : cl0_fun.

Definition arity (f : cl0_fun) : nat :=
match f with
| F_Conf => 3
| F_Pair => 2
| F_Trim => 1
| F_Split => 1
| F_Runtime => 2
end.

Section ARS.
Variable A : Type.
Variable R : A -> A -> Prop.

Inductive star : A -> A -> Prop :=
| star_refl : forall x, star x x
| star_step : forall x y z, R x y -> star y z -> star x z.

Definition joinable (x y : A) : Prop :=
exists z : A, star x z /\ star y z.

Definition WCR : Prop :=
forall a b c, R a b -> R a c -> joinable b c.

Definition CR : Prop :=
forall a b c, star a b -> star a c -> joinable b c.

Definition SN : Prop :=
forall x : A, exists n : nat, True.

Theorem star_trans : forall x y z, star x y -> star y z -> star x z.
Proof.
intros x y z Hxy.
induction Hxy as [x' | x' y' z' Hstep Hstar IH].
- intros Hyz. exact Hyz.
- intros Hyz. apply (star_step x' y' z Hstep). apply IH. exact Hyz.
Qed.

Lemma joinable_refl : forall x, joinable x x.
Proof.
intros x. exists x. split; apply star_refl.
Qed.

Lemma joinable_sym : forall x y, joinable x y -> joinable y x.
Proof.
intros x y [z [Hxz Hyz]].
exists z. split; assumption.
Qed.
End ARS.

Inductive dd_label : Set :=
| Label_Trim : nat -> dd_label
| Label_Split : nat -> dd_label
| Label_Runtime : nat -> dd_label.

Definition label_rank (l : dd_label) : nat :=
match l with
| Label_Trim _ => 1
| Label_Split _ => 2
| Label_Runtime _ => 3
end.

Definition label_lt (l1 l2 : dd_label) : Prop :=
label_rank l1 < label_rank l2.

Theorem lemma5_euler_characteristic_tree :
forall (e : nat),
S e - e = 1.
Proof.
induction e as [| e' IH].
- reflexivity.
- simpl. exact IH.
Qed.

Theorem lemma8_measure_strict_decrease :
forall (red_before red_after : nat),
red_after < red_before ->
red_before > 0.
Proof.
intros red_before red_after H.
destruct red_before as [| b'].
- inversion H.
- apply Peano.le_n_S. apply Peano.le_0_n.
Qed.

Record GaloisConnection (A B : Type) (f : A -> B) (g : B -> A) (leA : A -> A -> Prop) (leB : B -> B -> Prop) : Prop := {
galois_adjunction : forall a b, leB (f a) b <-> leA a (g b)
}.

Theorem span_monad_galois_trivial :
forall (A : Type) (le : A -> A -> Prop),
(forall a, le a a) ->
GaloisConnection A A (fun x => x) (fun x => x) le le.
Proof.
intros A le Hrefl.
split.
intros a b. split; intro H; exact H.
Qed.

Definition aeneas_swap (p : nat * nat) : (nat * nat) :=
match p with
| (x, y) => (y, x)
end.

Theorem aeneas_swap_involutive : forall p : nat * nat,
aeneas_swap (aeneas_swap p) = p.
Proof.
intros [x y]. simpl. reflexivity.
Qed.

